[tool.poetry]
name = "garuda"
version = "0.1.0"
description = ""
authors = ["raufer <raufer92@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pyspark = "^3.0.1"
pytest = "^6.1.2"
networkx = "^2.5"
pydantic = "^1.7.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
